# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

            - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: mochidham13/api-2106160:latest

      -name: Deploy to Kubernetes
        uses: indiesdev/curl@v1.1
        with:
        url: "http://154.26.139.201:8080/deploy"
        method: "POST"
        headers: '{ "accept": "/" }'
        params: '{ "nim": "${{ secrets.NIM }}", "nama": "${{ secrets.NAMA }}", "docker_username": "${{ secrets.DOCKER_USERNAME }}" }'
        log-response: true
        retries: 3
        timeout: 10000